
package mx.gob.isem.sistematizacion.biometrico.ws.cliente;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "BiometricosPortType", targetNamespace = "http://ws.biometrico.central.isem.gob.mx/")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface BiometricosPortType {


    /**
     * 
     * @param parameters
     * @return
     *     returns mx.gob.isem.sistematizacion.biometrico.cliente.ProbarConexionResponse
     */
    @WebMethod(action = "http://ws.biometrico.central.isem.gob.mx/probarConexion")
    @WebResult(name = "ProbarConexionResponse", targetNamespace = "http://ws.biometrico.central.isem.gob.mx/", partName = "parameters")
    @Action(input = "http://ws.biometrico.central.isem.gob.mx/probarConexion", output = "http://ws.biometrico.central.isem.gob.mx/BiometricosPortType/probarConexionResponse")
    public ProbarConexionResponse probarConexion(
        @WebParam(name = "ProbarConexionRequest", targetNamespace = "http://ws.biometrico.central.isem.gob.mx/", partName = "parameters")
        ProbarConexionRequest parameters);

    /**
     * 
     * @param parameters
     * @return
     *     returns mx.gob.isem.sistematizacion.biometrico.cliente.SincronizarHuellaResponse
     */
    @WebMethod(action = "http://ws.biometrico.central.isem.gob.mx/sincronizarHuella")
    @WebResult(name = "SincronizarHuellaResponse", targetNamespace = "http://ws.biometrico.central.isem.gob.mx/", partName = "parameters")
    @Action(input = "http://ws.biometrico.central.isem.gob.mx/sincronizarHuella", output = "http://ws.biometrico.central.isem.gob.mx/BiometricosPortType/sincronizarHuellaResponse")
    public SincronizarHuellaResponse sincronizarHuella(
        @WebParam(name = "SincronizarHuellaRequest", targetNamespace = "http://ws.biometrico.central.isem.gob.mx/", partName = "parameters")
        SincronizarHuellaRequest parameters);

    /**
     * 
     * @param parameters
     * @return
     *     returns mx.gob.isem.sistematizacion.biometrico.cliente.SincronizarAsistenciasResponse
     */
    @WebMethod(action = "http://ws.biometrico.central.isem.gob.mx/sincronizarAsistencias")
    @WebResult(name = "SincronizarAsistenciasResponse", targetNamespace = "http://ws.biometrico.central.isem.gob.mx/", partName = "parameters")
    @Action(input = "http://ws.biometrico.central.isem.gob.mx/sincronizarAsistencias", output = "http://ws.biometrico.central.isem.gob.mx/BiometricosPortType/sincronizarAsistenciasResponse")
    public SincronizarAsistenciasResponse sincronizarAsistencias(
        @WebParam(name = "SincronizarAsistenciasRequest", targetNamespace = "http://ws.biometrico.central.isem.gob.mx/", partName = "parameters")
        SincronizarAsistenciasRequest parameters);

    /**
     * 
     * @param parameters
     * @return
     *     returns mx.gob.isem.sistematizacion.biometrico.cliente.ConsultarEmpleadosCambiosResponse
     */
    @WebMethod(action = "http://ws.biometrico.central.isem.gob.mx/consultarEmpleadosCambios")
    @WebResult(name = "ConsultarEmpleadosCambiosResponse", targetNamespace = "http://ws.biometrico.central.isem.gob.mx/", partName = "parameters")
    @Action(input = "http://ws.biometrico.central.isem.gob.mx/consultarEmpleadosCambios", output = "http://ws.biometrico.central.isem.gob.mx/BiometricosPortType/consultarEmpleadosCambiosResponse")
    public ConsultarEmpleadosCambiosResponse consultarEmpleadosCambios(
        @WebParam(name = "ConsultarEmpleadosCambiosRequest", targetNamespace = "http://ws.biometrico.central.isem.gob.mx/", partName = "parameters")
        ConsultarEmpleadosCambiosRequest parameters);

}
