
package mx.gob.isem.sistematizacion.biometrico.ws.cliente;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "BiometricosService", targetNamespace = "http://ws.biometrico.central.isem.gob.mx/", wsdlLocation = "http://localhost:8080/ws/biometricos?wsdl")
public class BiometricosService
    extends Service
{

    private final static URL BIOMETRICOSSERVICE_WSDL_LOCATION;
    private final static WebServiceException BIOMETRICOSSERVICE_EXCEPTION;
    private final static QName BIOMETRICOSSERVICE_QNAME = new QName("http://ws.biometrico.central.isem.gob.mx/", "BiometricosService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8080/ws/biometricos?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        BIOMETRICOSSERVICE_WSDL_LOCATION = url;
        BIOMETRICOSSERVICE_EXCEPTION = e;
    }

    public BiometricosService() {
        super(__getWsdlLocation(), BIOMETRICOSSERVICE_QNAME);
    }

    public BiometricosService(WebServiceFeature... features) {
        super(__getWsdlLocation(), BIOMETRICOSSERVICE_QNAME, features);
    }

    public BiometricosService(URL wsdlLocation) {
        super(wsdlLocation, BIOMETRICOSSERVICE_QNAME);
    }

    public BiometricosService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, BIOMETRICOSSERVICE_QNAME, features);
    }

    public BiometricosService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public BiometricosService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns BiometricosPortType
     */
    @WebEndpoint(name = "BiometricosPort")
    public BiometricosPortType getBiometricosPort() {
        return super.getPort(new QName("http://ws.biometrico.central.isem.gob.mx/", "BiometricosPort"), BiometricosPortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns BiometricosPortType
     */
    @WebEndpoint(name = "BiometricosPort")
    public BiometricosPortType getBiometricosPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://ws.biometrico.central.isem.gob.mx/", "BiometricosPort"), BiometricosPortType.class, features);
    }

    private static URL __getWsdlLocation() {
        if (BIOMETRICOSSERVICE_EXCEPTION!= null) {
            throw BIOMETRICOSSERVICE_EXCEPTION;
        }
        return BIOMETRICOSSERVICE_WSDL_LOCATION;
    }

}
